package models;
// Generated 2010-9-30 9:29:35 by Hibernate Tools 3.3.0.GA


import javax.persistence.Entity;
import javax.persistence.Table;

import play.db.jpa.Model;


/**
 * Posts generated by hbm2java
 */
@Entity
@Table(name = "t_posts")
public class Posts extends  Model {

	public final static int Status_UnAduit =0;  //未审核
	public final static int Status_Aduit =1;    //已审核
	public final static int Status_Delete =3;	//已删除
	
	public static enum CHANNEL{
		PANGUKE,MITALK,ISH
	}
	/**
	 * 
	 */
	public User user;
	public String message;
	public short mentioned;
	public String attachedLink;
	public boolean attachments;
	public int date;
	public short stockState;
	public long ipAddress;
	public boolean isFeed;
	public int parentId;
	public int copyNums;
	public int reviewNums;
	public int status;
	public String source;
	public int praise;
	
	/** 
	* @Fields viewMessage : 加链接后的微博内容
	*/ 
	public String viewMessage;
	
	/** 
	* @Fields channel : 来源类型
	*/ 
	public  CHANNEL channel;
	
	/** 
	* @Fields channelId :来源具体的ID
	*/ 
	public Integer channelId;
	
	/** 
	* @Fields sourceStr : 新的来源显示内容
	*/ 
	public String sourceStr;
	
	public PostsAttachments attachs;
	
	public Posts parentPosts;
	
	
	
}
